# TCL File Generated by Component Editor 21.1
# Wed Apr 15 16:36:49 EDT 2026
# DO NOT MODIFY


# 
# fighter_audio "Fighter_Audio" v1.0
#  2026.04.15.16:36:49
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module fighter_audio
# 
set_module_property DESCRIPTION ""
set_module_property NAME fighter_audio
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Fighter_Audio
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false

set_module_assignment embeddedsw.dts.vendor "csee4840"
set_module_assignment embeddedsw.dts.name "fighter_audio"
set_module_assignment embeddedsw.dts.group "audio"

# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL fighter_audio_wm8731
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file fighter_audio.sv SYSTEM_VERILOG PATH fighter_audio.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter FIFO_DEPTH STRING 128
set_parameter_property FIFO_DEPTH DEFAULT_VALUE 128
set_parameter_property FIFO_DEPTH DISPLAY_NAME FIFO_DEPTH
set_parameter_property FIFO_DEPTH TYPE STRING
set_parameter_property FIFO_DEPTH UNITS None
set_parameter_property FIFO_DEPTH HDL_PARAMETER true
add_parameter CLK_HZ STRING 50000000
set_parameter_property CLK_HZ DEFAULT_VALUE 50000000
set_parameter_property CLK_HZ DISPLAY_NAME CLK_HZ
set_parameter_property CLK_HZ TYPE STRING
set_parameter_property CLK_HZ UNITS None
set_parameter_property CLK_HZ HDL_PARAMETER true
add_parameter I2C_RATE_HZ STRING 100000
set_parameter_property I2C_RATE_HZ DEFAULT_VALUE 100000
set_parameter_property I2C_RATE_HZ DISPLAY_NAME I2C_RATE_HZ
set_parameter_property I2C_RATE_HZ TYPE STRING
set_parameter_property I2C_RATE_HZ UNITS None
set_parameter_property I2C_RATE_HZ HDL_PARAMETER true
add_parameter XCK_DIV STRING 4
set_parameter_property XCK_DIV DEFAULT_VALUE 4
set_parameter_property XCK_DIV DISPLAY_NAME XCK_DIV
set_parameter_property XCK_DIV TYPE STRING
set_parameter_property XCK_DIV UNITS None
set_parameter_property XCK_DIV HDL_PARAMETER true
add_parameter BCLK_DIV STRING 16
set_parameter_property BCLK_DIV DEFAULT_VALUE 16
set_parameter_property BCLK_DIV DISPLAY_NAME BCLK_DIV
set_parameter_property BCLK_DIV TYPE STRING
set_parameter_property BCLK_DIV UNITS None
set_parameter_property BCLK_DIV HDL_PARAMETER true
add_parameter I2C_DEVICE_ADDR STD_LOGIC_VECTOR 26
set_parameter_property I2C_DEVICE_ADDR DEFAULT_VALUE 26
set_parameter_property I2C_DEVICE_ADDR DISPLAY_NAME I2C_DEVICE_ADDR
set_parameter_property I2C_DEVICE_ADDR TYPE STD_LOGIC_VECTOR
set_parameter_property I2C_DEVICE_ADDR UNITS None
set_parameter_property I2C_DEVICE_ADDR ALLOWED_RANGES 0:255
set_parameter_property I2C_DEVICE_ADDR HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 avs_chipselect chipselect Input 1
add_interface_port avalon_slave_0 avs_read read Input 1
add_interface_port avalon_slave_0 avs_write write Input 1
add_interface_port avalon_slave_0 avs_address address Input 2
add_interface_port avalon_slave_0 avs_writedata writedata Input 32
add_interface_port avalon_slave_0 avs_readdata readdata Output 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point audio
# 
add_interface audio conduit end
set_interface_property audio associatedClock clock
set_interface_property audio associatedReset ""
set_interface_property audio ENABLED true
set_interface_property audio EXPORT_OF ""
set_interface_property audio PORT_NAME_MAP ""
set_interface_property audio CMSIS_SVD_VARIABLES ""
set_interface_property audio SVD_ADDRESS_GROUP ""

add_interface_port audio aud_adcdat adcdat Input 1
add_interface_port audio aud_adclrck adclrck Output 1
add_interface_port audio aud_bclk bclk Output 1
add_interface_port audio aud_dacdat dacdat Output 1
add_interface_port audio aud_daclrck daclrck Output 1
add_interface_port audio aud_xck xck Output 1
add_interface_port audio codec_init_done init_done Output 1
add_interface_port audio codec_init_error init_error Output 1
add_interface_port audio fpga_i2c_sclk i2c_sclk Bidir 1
add_interface_port audio fpga_i2c_sdat i2c_sdat Bidir 1

