# TCL File Generated by Component Editor 21.1
# Corrected for integer HDL parameters

package require -exact qsys 16.1

#
# module fighter_audio
#
set_module_property DESCRIPTION ""
set_module_property NAME fighter_audio
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME fighterAudio
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false

#
# file sets
#
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL fighter_audio_wm8731
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file fighter_audio.sv SYSTEM_VERILOG PATH fighter_audio.sv TOP_LEVEL_FILE

#
# parameters
#
add_parameter FIFO_DEPTH INTEGER 128
set_parameter_property FIFO_DEPTH DEFAULT_VALUE 128
set_parameter_property FIFO_DEPTH DISPLAY_NAME FIFO_DEPTH
set_parameter_property FIFO_DEPTH TYPE INTEGER
set_parameter_property FIFO_DEPTH UNITS None
set_parameter_property FIFO_DEPTH HDL_PARAMETER true

add_parameter CLK_HZ INTEGER 50000000
set_parameter_property CLK_HZ DEFAULT_VALUE 50000000
set_parameter_property CLK_HZ DISPLAY_NAME CLK_HZ
set_parameter_property CLK_HZ TYPE INTEGER
set_parameter_property CLK_HZ UNITS None
set_parameter_property CLK_HZ HDL_PARAMETER true

add_parameter I2C_RATE_HZ INTEGER 100000
set_parameter_property I2C_RATE_HZ DEFAULT_VALUE 100000
set_parameter_property I2C_RATE_HZ DISPLAY_NAME I2C_RATE_HZ
set_parameter_property I2C_RATE_HZ TYPE INTEGER
set_parameter_property I2C_RATE_HZ UNITS None
set_parameter_property I2C_RATE_HZ HDL_PARAMETER true

add_parameter XCK_DIV INTEGER 4
set_parameter_property XCK_DIV DEFAULT_VALUE 4
set_parameter_property XCK_DIV DISPLAY_NAME XCK_DIV
set_parameter_property XCK_DIV TYPE INTEGER
set_parameter_property XCK_DIV UNITS None
set_parameter_property XCK_DIV HDL_PARAMETER true

add_parameter BCLK_DIV INTEGER 16
set_parameter_property BCLK_DIV DEFAULT_VALUE 16
set_parameter_property BCLK_DIV DISPLAY_NAME BCLK_DIV
set_parameter_property BCLK_DIV TYPE INTEGER
set_parameter_property BCLK_DIV UNITS None
set_parameter_property BCLK_DIV HDL_PARAMETER true

add_parameter I2C_DEVICE_ADDR STD_LOGIC_VECTOR 26
set_parameter_property I2C_DEVICE_ADDR DEFAULT_VALUE 26
set_parameter_property I2C_DEVICE_ADDR DISPLAY_NAME I2C_DEVICE_ADDR
set_parameter_property I2C_DEVICE_ADDR WIDTH 8
set_parameter_property I2C_DEVICE_ADDR TYPE STD_LOGIC_VECTOR
set_parameter_property I2C_DEVICE_ADDR UNITS None
set_parameter_property I2C_DEVICE_ADDR ALLOWED_RANGES 0:255
set_parameter_property I2C_DEVICE_ADDR HDL_PARAMETER true

#
# module assignments
#
set_module_assignment embeddedsw.dts.group audio
set_module_assignment embeddedsw.dts.name fighter_audio
set_module_assignment embeddedsw.dts.vendor csee4840

#
# connection point clock
#
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1

#
# connection point reset
#
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1

#
# connection point avalon_slave_0
#
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 avs_chipselect chipselect Input 1
add_interface_port avalon_slave_0 avs_read read Input 1
add_interface_port avalon_slave_0 avs_write write Input 1
add_interface_port avalon_slave_0 avs_address address Input 2
add_interface_port avalon_slave_0 avs_writedata writedata Input 32
add_interface_port avalon_slave_0 avs_readdata readdata Output 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0

#
# connection point fighter_audio
#
add_interface fighter_audio conduit end
set_interface_property fighter_audio associatedClock clock
set_interface_property fighter_audio associatedReset ""
set_interface_property fighter_audio ENABLED true
set_interface_property fighter_audio EXPORT_OF ""
set_interface_property fighter_audio PORT_NAME_MAP ""
set_interface_property fighter_audio CMSIS_SVD_VARIABLES ""
set_interface_property fighter_audio SVD_ADDRESS_GROUP ""

add_interface_port fighter_audio aud_adcdat        audio_adcdat     Input 1
add_interface_port fighter_audio aud_adclrck       audio_adclrck    Output 1
add_interface_port fighter_audio aud_bclk          audio_bclk       Output 1
add_interface_port fighter_audio aud_dacdat        audio_dacdat     Output 1
add_interface_port fighter_audio aud_daclrck       aud_daclrck      Output 1
add_interface_port fighter_audio aud_xck           audio_xck        Output 1
add_interface_port fighter_audio codec_init_done   audio_init_done  Output 1
add_interface_port fighter_audio codec_init_error  audio_init_error Output 1
add_interface_port fighter_audio fpga_i2c_sclk     audio_i2c_sclk   Bidir 1
add_interface_port fighter_audio fpga_i2c_sdat     audio_i2c_sdat   Bidir 1
