#ifndef FIGHTER_VGA_MMIO_H
#define FIGHTER_VGA_MMIO_H

enum {
  FIGHTER_VGA_MMIO_REG_CONTROL = 0,
  FIGHTER_VGA_MMIO_REG_WIDTH = 1,
  FIGHTER_VGA_MMIO_REG_HEIGHT = 2,
  FIGHTER_VGA_MMIO_REG_STRIDE = 3,
  FIGHTER_VGA_MMIO_REG_IDENT = 31,
  FIGHTER_VGA_MMIO_REG_FRAME_WORD_OFFSET = 1024,

  FIGHTER_VGA_MMIO_FRAME_WIDTH = 320,
  FIGHTER_VGA_MMIO_FRAME_HEIGHT = 240,
  FIGHTER_VGA_MMIO_FRAME_WORD_COUNT =
      (FIGHTER_VGA_MMIO_FRAME_WIDTH * FIGHTER_VGA_MMIO_FRAME_HEIGHT) / 2,
  FIGHTER_VGA_MMIO_REG_SPAN_COUNT =
      FIGHTER_VGA_MMIO_REG_FRAME_WORD_OFFSET +
      FIGHTER_VGA_MMIO_FRAME_WORD_COUNT
};

#define FIGHTER_VGA_MMIO_CONTROL_PRESENT (1U << 0)
#define FIGHTER_VGA_MMIO_CONTROL_SWAP_REQUEST (1U << 1)
#define FIGHTER_VGA_MMIO_CONTROL_SWAP_PENDING (1U << 1)
#define FIGHTER_VGA_MMIO_CONTROL_DISPLAY_BUFFER (1U << 8)
#define FIGHTER_VGA_MMIO_CONTROL_WRITE_BUFFER (1U << 9)

#endif
