#ifndef FIGHTER_MMIO_H
#define FIGHTER_MMIO_H

#include <stdint.h>

#include "fighter_game.h"

#ifdef __cplusplus
extern "C" {
#endif

enum {
  FIGHTER_MMIO_REG_GAME_STATE = 0,
  FIGHTER_MMIO_REG_PLAYER1_X,
  FIGHTER_MMIO_REG_PLAYER1_Y,
  FIGHTER_MMIO_REG_PLAYER1_STATE,
  FIGHTER_MMIO_REG_PLAYER2_X,
  FIGHTER_MMIO_REG_PLAYER2_Y,
  FIGHTER_MMIO_REG_PLAYER2_STATE,
  FIGHTER_MMIO_REG_PLAYER1_HP,
  FIGHTER_MMIO_REG_PLAYER2_HP,
  FIGHTER_MMIO_REG_ROUND_TIMER,
  FIGHTER_MMIO_REG_WINNER,
  FIGHTER_MMIO_REG_PLAYER1_FACING,
  FIGHTER_MMIO_REG_PLAYER2_FACING,
  FIGHTER_MMIO_REG_DEBUG_FLAGS,
  FIGHTER_MMIO_REG_PLAYER1_ATTACK_CMD,
  FIGHTER_MMIO_REG_PLAYER2_ATTACK_CMD,
  FIGHTER_MMIO_REG_PLAYER1_STATE_FRAME,
  FIGHTER_MMIO_REG_PLAYER2_STATE_FRAME,
  FIGHTER_MMIO_REG_PLAYER1_EVENT_FLAGS,
  FIGHTER_MMIO_REG_PLAYER2_EVENT_FLAGS,
  FIGHTER_MMIO_REG_PLAYER1_COMBAT_RESULT,
  FIGHTER_MMIO_REG_PLAYER2_COMBAT_RESULT,
  FIGHTER_MMIO_REG_COUNT,

  FIGHTER_MMIO_REG_IDENT = 31,
  FIGHTER_MMIO_REG_SPAN_COUNT = 32
};

void fighter_mmio_encode(const fighter_game_t *game,
                         uint32_t regs[FIGHTER_MMIO_REG_COUNT]);

#ifdef __cplusplus
}
#endif

#endif
